general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: gemini-2.0-flash-001
    litellm_params:
      model: vertex_ai/gemini-2.0-flash-001
      vertex_project: sunivy-for-example
      vertex_location: us-central1
  - model_name: gemini-2.5-pro-exp
    litellm_params:
      model: vertex_ai/gemini-2.5-pro-exp-03-25
      vertex_project: sunivy-for-example
      vertex_location: us-central1

litellm_settings:
  vertex_ai_safety_settings:
    - category: HARM_CATEGORY_HARASSMENT
      threshold: BLOCK_NONE
    - category: HARM_CATEGORY_HATE_SPEECH
      threshold: BLOCK_NONE
    - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
      threshold: BLOCK_NONE
    - category: HARM_CATEGORY_DANGEROUS_CONTENT
      threshold: BLOCK_NONE



